app:
  version: 1.0.0 # [STRING]
  api:
    collector: localhost:9060

http_server:
  port: 9070 # [INTEGER]
  read_header_timeout: 10s # [TIME.DURATION]
  read_timeout: 20s # [TIME.DURATION]
  write_timeout: 20s # [TIME.DURATION]
  idle_timeout: 1m # [TIME.DURATION]

logging:
  enable: true # [BOOLEAN]
  level: DEBUG # [STRING] - Available levels: INFO, WARNING, ERROR.
