app:
  version: 1.0.0 # [STRING]

grpc:
  port: 9060 # [INTEGER]

database:
  migration:
    dir: "./migrations"
  postgres:
    url: "host=localhost port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"

logging:
  enable: true # [BOOLEAN]
  level: DEBUG # [STRING] - Available levels: INFO, WARNING, ERROR.
